
-- Eliminar solo los registros de posicion_movimientos que no estén siendo utilizados en análisis
DELETE FROM posicion_movimientos 
WHERE id NOT IN (
  SELECT DISTINCT posicion_movimiento_id 
  FROM analisis_videos 
  WHERE posicion_movimiento_id IS NOT NULL
);

-- Insertar los nuevos movimientos y características
INSERT INTO posicion_movimientos (
  posicion_id, 
  nombre_movimiento, 
  caracteristica_1, 
  caracteristica_2, 
  caracteristica_3, 
  caracteristica_4, 
  caracteristica_5
) 
SELECT 
  p.id as posicion_id,
  movimiento_data.nombre_movimiento,
  movimiento_data.caracteristica_1,
  movimiento_data.caracteristica_2,
  movimiento_data.caracteristica_3,
  movimiento_data.caracteristica_4,
  movimiento_data.caracteristica_5
FROM (
  VALUES 
    -- Baloncesto
    ('Baloncesto', 'Base', 'Visión de juego', 'Lectura de la defensa', 'Identificación de compañeros abiertos', 'Anticipación de jugadas', 'Capacidad para encontrar pases', 'Control del tempo'),
    ('Baloncesto', 'Base', 'Manejo de balón', 'Dribbling con ambas manos', 'Cambios de dirección', 'Protección del balón', 'Control de la velocidad', 'Manejo bajo presión'),
    ('Baloncesto', 'Base', 'Pase', 'Precisión en el pase', 'Variedad de pases', 'Pase con ambas manos', 'Pase sin mirar', 'Pase bajo presión'),
    ('Baloncesto', 'Base', 'Liderazgo', 'Comunicación en cancha', 'Organización del equipo', 'Calma bajo presión', 'Motivación a compañeros', 'Toma de decisiones rápidas'),
    ('Baloncesto', 'Base', 'Tiro exterior', 'Mecánica de tiro', 'Selección de tiro', 'Consistencia', 'Tiro tras drible', 'Tiro bajo presión'),
    ('Baloncesto', 'Escolta', 'Capacidad anotadora', 'Variedad de tiros', 'Consistencia en el tiro', 'Creación de sus propios tiros', 'Anotación en diferentes situaciones', 'Eficacia en el clutch'),
    ('Baloncesto', 'Escolta', 'Tiro de media distancia', 'Mecánica de tiro', 'Consistencia', 'Tiro tras drible', 'Tiro en suspensión', 'Tiro desde el poste'),
    ('Baloncesto', 'Escolta', 'Movimientos sin balón', 'Cortes a canasta', 'Desmarques', 'Ubicación para el rebote ofensivo', 'Creación de espacio', 'Lectura de la defensa'),
    ('Baloncesto', 'Escolta', 'Defensa exterior', 'Velocidad lateral', 'Marcaje 1vs1', 'Robo de balón', 'Defensa de pick and roll', 'Cierre de líneas de pase'),
    ('Baloncesto', 'Escolta', 'Creación de espacio', 'Bloqueos sin balón', 'Cortes', 'Movimientos de engaño', 'Atraer defensores', 'Sacar faltas'),
    ('Baloncesto', 'Alero', 'Versatilidad ofensiva', 'Tiro exterior', 'Penetración', 'Posteo', 'Juego sin balón', 'Asistencia'),
    ('Baloncesto', 'Alero', 'Rebote', 'Posicionamiento', 'Salto vertical', 'Fuerza para ganar la posición', 'Lectura del rebote', 'Protección del balón tras rebote'),
    ('Baloncesto', 'Alero', 'Defensa 1vs1', 'Velocidad lateral', 'Marcaje', 'Anticipación', 'Recuperación', 'Defensa posteo'),
    ('Baloncesto', 'Alero', 'Capacidad de penetración', 'Primer paso', 'Control de balón en carrera', 'Finalización cerca del aro', 'Habilidad para sacar faltas', 'Cambios de ritmo'),
    ('Baloncesto', 'Alero', 'Tiro de 3 puntos', 'Mecánica de tiro', 'Consistencia', 'Tiro en catch and shoot', 'Tiro tras drible', 'Tiro desde las esquinas'),
    ('Baloncesto', 'Ala-pívot', 'Posteo', 'Movimientos de espaldas al aro', 'Ganchos', 'Fuerza en el poste bajo', 'Juego de pies', 'Pases desde el poste'),
    ('Baloncesto', 'Ala-pívot', 'Rebote defensivo', 'Posicionamiento', 'Bloqueo de rebote', 'Salto vertical', 'Fuerza', 'Comunicación para el rebote'),
    ('Baloncesto', 'Ala-pívot', 'Tiro de media distancia', 'Mecánica de tiro', 'Consistencia', 'Tiro en suspensión', 'Tiro tras bloqueo', 'Tiro desde la zona de media'),
    ('Baloncesto', 'Ala-pívot', 'Defensa interior', 'Defensa al poste bajo', 'Bloqueos', 'Ayudas defensivas', 'Anticipación de pases', 'Intimidación'),
    ('Baloncesto', 'Ala-pívot', 'Bloqueos', 'Fuerza en el bloqueo', 'Precisión del bloqueo', 'Continuidad tras bloqueo', 'Bloqueo para el tirador', 'Bloqueo para la penetración'),
    ('Baloncesto', 'Pívot', 'Rebote ofensivo', 'Posicionamiento', 'Salto', 'Fuerza para ganar la posición', 'Agresividad en el rebote', 'Lectura del rebote'),
    ('Baloncesto', 'Pívot', 'Bloqueos', 'Fuerza en el bloqueo', 'Precisión del bloqueo', 'Continuidad tras bloqueo', 'Bloqueo para el tirador', 'Bloqueo para la penetración'),
    ('Baloncesto', 'Pívot', 'Finalización cerca del aro', 'Ganchos', 'Bandejas', 'Mate', 'Tiros de corta distancia', 'Habilidad para recibir pases difíciles'),
    ('Baloncesto', 'Pívot', 'Defensa interior', 'Defensa al poste bajo', 'Bloqueos', 'Ayudas defensivas', 'Intimidación', 'Protección del aro'),
    ('Baloncesto', 'Pívot', 'Presencia en la pintura', 'Capacidad para atraer faltas', 'Rebote', 'Defensa de la zona', 'Bloqueos', 'Intimidación'),
    
    -- Fútbol
    ('Fútbol', 'Portero', 'Reflejos', 'Velocidad de reacción', 'Agilidad', 'Movimientos rápidos', 'Capacidad de parada', 'Anticipación'),
    ('Fútbol', 'Portero', 'Colocación', 'Posicionamiento bajo los tres palos', 'Ángulo de cobertura', 'Posición en los saques de esquina', 'Cobertura del área', 'Lectura de la jugada'),
    ('Fútbol', 'Portero', 'Juego aéreo', 'Salida por alto', 'Dominio del área pequeña', 'Puñetazos', 'Agarres', 'Comunicación'),
    ('Fútbol', 'Portero', 'Comunicación', 'Organización de la defensa', 'Gritos de mando', 'Claridad en las indicaciones', 'Confianza', 'Entendimiento con la defensa'),
    ('Fútbol', 'Portero', 'Saque', 'Precisión del saque de meta', 'Potencia del saque', 'Saque de mano', 'Saque de volea', 'Lectura del juego para el saque'),
    ('Fútbol', 'Defensa central', 'Marcaje', 'Marcaje individual', 'Marcaje zonal', 'Capacidad de anticipación', 'Fuerza en el choque', 'Coberturas'),
    ('Fútbol', 'Defensa central', 'Juego aéreo defensivo', 'Remate de cabeza defensivo', 'Posicionamiento en balones aéreos', 'Salto', 'Fuerza', 'Anticipación'),
    ('Fútbol', 'Defensa central', 'Salida de balón', 'Pase en corto', 'Pase en largo', 'Visión de juego', 'Conducción', 'Presión tras pérdida'),
    ('Fútbol', 'Defensa central', 'Anticipación', 'Lectura de juego', 'Intercepción de pases', 'Cortes de jugada', 'Posicionamiento preventivo', 'Reacción rápida'),
    ('Fútbol', 'Defensa central', 'Liderazgo en defensa', 'Organización de la línea defensiva', 'Comunicación', 'Gritos de mando', 'Capacidad para corregir', 'Calma bajo presión'),
    ('Fútbol', 'Lateral derecho', 'Subida por banda', 'Velocidad', 'Resistencia', 'Desborde', 'Centros', 'Apoyo ofensivo'),
    ('Fútbol', 'Lateral derecho', 'Centros', 'Precisión del centro', 'Variedad de centros', 'Centro en movimiento', 'Centro al primer toque', 'Centro tras regate'),
    ('Fútbol', 'Lateral derecho', 'Repliegue defensivo', 'Velocidad de repliegue', 'Marcaje al extremo', 'Cobertura del central', 'Intensidad defensiva', 'Capacidad para recuperar'),
    ('Fútbol', 'Lateral derecho', 'Resistencia', 'Capacidad aeróbica', 'Recorrido', 'Mantenimiento del ritmo', 'Recuperación entre esfuerzos', 'Aguante físico'),
    ('Fútbol', 'Lateral derecho', 'Marcaje al extremo', 'Velocidad lateral', 'Anticipación', 'Entrada', 'Cobertura', 'Presión'),
    ('Fútbol', 'Lateral izquierdo', 'Subida por banda', 'Velocidad', 'Resistencia', 'Desborde', 'Centros', 'Apoyo ofensivo'),
    ('Fútbol', 'Lateral izquierdo', 'Centros', 'Precisión del centro', 'Variedad de centros', 'Centro en movimiento', 'Centro al primer toque', 'Centro tras regate'),
    ('Fútbol', 'Lateral izquierdo', 'Repliegue defensivo', 'Velocidad de repliegue', 'Marcaje al extremo', 'Cobertura del central', 'Intensidad defensiva', 'Capacidad para recuperar'),
    ('Fútbol', 'Lateral izquierdo', 'Resistencia', 'Capacidad aeróbica', 'Recorrido', 'Mantenimiento del ritmo', 'Recuperación entre esfuerzos', 'Aguante físico'),
    ('Fútbol', 'Lateral izquierdo', 'Marcaje al extremo', 'Velocidad lateral', 'Anticipación', 'Entrada', 'Cobertura', 'Presión'),
    ('Fútbol', 'Carrilero', 'Recorrido', 'Resistencia', 'Velocidad', 'Capacidad aeróbica', 'Mantenimiento del ritmo', 'Recuperación'),
    ('Fútbol', 'Carrilero', 'Centros', 'Precisión del centro', 'Variedad de centros', 'Centro en movimiento', 'Centro al primer toque', 'Centro tras regate'),
    ('Fútbol', 'Carrilero', 'Defensa en banda', 'Marcaje', 'Repliegue', 'Anticipación', 'Cobertura', 'Presión'),
    ('Fútbol', 'Carrilero', 'Resistencia', 'Capacidad aeróbica', 'Recorrido', 'Mantenimiento del ritmo', 'Recuperación entre esfuerzos', 'Aguante físico'),
    ('Fútbol', 'Carrilero', 'Apoyo ofensivo y defensivo', 'Transiciones', 'Balance', 'Coberturas', 'Desdoble', 'Ayudas'),
    ('Fútbol', 'Mediocentro defensivo', 'Recuperación de balón', 'Intercepción', 'Entrada', 'Anticipación', 'Presión', 'Marcaje'),
    ('Fútbol', 'Mediocentro defensivo', 'Posicionamiento defensivo', 'Cobertura', 'Balance', 'Lectura de la jugada', 'Cierre de espacios', 'Vigilancia de marca'),
    ('Fútbol', 'Mediocentro defensivo', 'Distribución de juego', 'Pase corto', 'Pase largo', 'Visión de juego', 'Cambio de orientación', 'Control de ritmo'),
    ('Fútbol', 'Mediocentro defensivo', 'Interceptación', 'Lectura de pases', 'Cortes', 'Anticipación', 'Posicionamiento', 'Velocidad de reacción'),
    ('Fútbol', 'Mediocentro defensivo', 'Primer pase', 'Pase seguro', 'Pase con ventaja', 'Salida de presión', 'Visión de juego', 'Pase en corto y largo'),
    ('Fútbol', 'Mediocentro', 'Visión de juego', 'Lectura de la jugada', 'Pase filtrado', 'Cambio de orientación', 'Identificación de espacios', 'Anticipación'),
    ('Fútbol', 'Mediocentro', 'Pase', 'Precisión en el pase', 'Variedad de pases', 'Pase en profundidad', 'Pase bajo presión', 'Pase con ambas piernas'),
    ('Fútbol', 'Mediocentro', 'Control de ritmo', 'Manejo del balón', 'Distribución', 'Pausa', 'Aceleración de juego', 'Toma de decisiones'),
    ('Fútbol', 'Mediocentro', 'Llegada al área', 'Desmarque', 'Remate', 'Tiro de media distancia', 'Apoyo ofensivo', 'Capacidad de definición'),
    ('Fútbol', 'Mediocentro', 'Apoyo ofensivo y defensivo', 'Transiciones', 'Balance', 'Coberturas', 'Desdoble', 'Ayudas'),
    ('Fútbol', 'Mediocentro ofensivo', 'Regate', 'Cambio de ritmo', 'Habilidad con el balón', 'Dribbling en espacios reducidos', 'Desborde', 'Creatividad'),
    ('Fútbol', 'Mediocentro ofensivo', 'Pase al hueco', 'Precisión', 'Timing', 'Visión de juego', 'Pase sin mirar', 'Pase bajo presión'),
    ('Fútbol', 'Mediocentro ofensivo', 'Disparo a puerta', 'Potencia de tiro', 'Precisión del tiro', 'Tiro de media distancia', 'Tiro con ambas piernas', 'Selección de tiro'),
    ('Fútbol', 'Mediocentro ofensivo', 'Creación de juego', 'Asistencias', 'Pase clave', 'Movimiento sin balón', 'Combinaciones', 'Desequilibrio'),
    ('Fútbol', 'Mediocentro ofensivo', 'Visión de gol', 'Posicionamiento', 'Remate', 'Aprovechamiento de oportunidades', 'Instinto goleador', 'Definición'),
    ('Fútbol', 'Extremo derecho', 'Velocidad', 'Aceleración', 'Punta', 'Cambio de ritmo', 'Velocidad con balón', 'Sin balón'),
    ('Fútbol', 'Extremo derecho', 'Regate', 'Dribbling', 'Cambios de dirección', 'Habilidad para superar al defensor', 'Fintas', 'Creatividad'),
    ('Fútbol', 'Extremo derecho', 'Centro', 'Precisión del centro', 'Variedad de centros', 'Centro en movimiento', 'Centro al primer toque', 'Centro tras regate'),
    ('Fútbol', 'Extremo derecho', 'Desborde', 'Capacidad para superar al rival', 'Velocidad', 'Habilidad', 'Picardía', 'Determinación'),
    ('Fútbol', 'Extremo derecho', 'Tiro a puerta', 'Precisión', 'Potencia', 'Tiro de media distancia', 'Tiro con ambas piernas', 'Selección de tiro'),
    ('Fútbol', 'Extremo izquierdo', 'Velocidad', 'Aceleración', 'Punta', 'Cambio de ritmo', 'Velocidad con balón', 'Sin balón'),
    ('Fútbol', 'Extremo izquierdo', 'Regate', 'Dribbling', 'Cambios de dirección', 'Habilidad para superar al defensor', 'Fintas', 'Creatividad'),
    ('Fútbol', 'Extremo izquierdo', 'Centro', 'Precisión del centro', 'Variedad de centros', 'Centro en movimiento', 'Centro al primer toque', 'Centro tras regate'),
    ('Fútbol', 'Extremo izquierdo', 'Desborde', 'Capacidad para superar al rival', 'Velocidad', 'Habilidad', 'Picardía', 'Determinación'),
    ('Fútbol', 'Extremo izquierdo', 'Tiro a puerta', 'Precisión', 'Potencia', 'Tiro de media distancia', 'Tiro con ambas piernas', 'Selección de tiro'),
    ('Fútbol', 'Segundo delantero', 'Movilidad', 'Desmarques', 'Movimiento sin balón', 'Creación de espacios', 'Intercambio de posiciones', 'Inteligencia táctica'),
    ('Fútbol', 'Segundo delantero', 'Desmarque', 'Desmarque al espacio', 'Desmarque de apoyo', 'Desmarque de ruptura', 'Timing', 'Lectura de la jugada'),
    ('Fútbol', 'Segundo delantero', 'Asistencia', 'Pase final', 'Último pase', 'Visión de juego', 'Pase al hueco', 'Creatividad'),
    ('Fútbol', 'Segundo delantero', 'Disparo a puerta', 'Precisión', 'Potencia', 'Tiro de media distancia', 'Tiro con ambas piernas', 'Selección de tiro'),
    ('Fútbol', 'Segundo delantero', 'Presión al defensor', 'Intensidad en la presión', 'Dirección de la presión', 'Recuperación de balón', 'Agresividad', 'Resistencia'),
    ('Fútbol', 'Delantero centro', 'Definición', 'Precisión en el tiro', 'Potencia de tiro', 'Capacidad de finalización', 'Tiro con ambas piernas', 'Remate de primera'),
    ('Fútbol', 'Delantero centro', 'Desmarque', 'Desmarque al espacio', 'Desmarque de ruptura', 'Desmarque de apoyo', 'Timing', 'Lectura de la jugada'),
    ('Fútbol', 'Delantero centro', 'Juego de espaldas', 'Protección del balón', 'Pase de apoyo', 'Giro', 'Retención de balón', 'Movimientos en el poste'),
    ('Fútbol', 'Delantero centro', 'Remate de cabeza', 'Precisión del remate', 'Potencia del remate', 'Salto', 'Posicionamiento', 'Anticipación'),
    ('Fútbol', 'Delantero centro', 'Presencia en el área', 'Posicionamiento', 'Intensidad', 'Capacidad para ganar la posición', 'Remate', 'Sacar faltas'),
    
    -- Balonmano
    ('Balonmano', 'Portero', 'Reflejos', 'Velocidad de reacción', 'Agilidad', 'Movimientos rápidos', 'Capacidad de parada', 'Anticipación'),
    ('Balonmano', 'Portero', 'Salida de balón', 'Precisión en el pase', 'Velocidad en el saque', 'Pase al contraataque', 'Saque en largo', 'Visión de juego'),
    ('Balonmano', 'Portero', 'Juego de pies', 'Movilidad en la portería', 'Rapidez de movimientos', 'Coordinación', 'Desplazamiento lateral', 'Posicionamiento'),
    ('Balonmano', 'Portero', 'Comunicación', 'Organización de la defensa', 'Gritos de mando', 'Claridad en las indicaciones', 'Confianza', 'Entendimiento con la defensa'),
    ('Balonmano', 'Portero', 'Lectura de lanzamiento', 'Anticipación del tiro', 'Identificación de patrones', 'Conocimiento de los lanzadores', 'Reacción a la finta', 'Colocación'),
    ('Balonmano', 'Central', 'Visión de juego', 'Lectura de la defensa', 'Identificación de espacios', 'Pase al pivote', 'Pase al extremo', 'Organización ofensiva'),
    ('Balonmano', 'Central', 'Pase', 'Precisión en el pase', 'Variedad de pases', 'Pase rápido', 'Pase al pivote', 'Pase al extremo'),
    ('Balonmano', 'Central', 'Liderazgo', 'Comunicación en cancha', 'Organización del ataque', 'Calma bajo presión', 'Toma de decisiones rápidas', 'Motivación a compañeros'),
    ('Balonmano', 'Central', 'Cambio de ritmo', 'Aceleración', 'Frenada', 'Desborde', 'Coordinación', 'Agilidad'),
    ('Balonmano', 'Central', 'Lanzamiento exterior', 'Potencia de lanzamiento', 'Precisión de lanzamiento', 'Tiro a portería', 'Variedad de lanzamientos', 'Lanzamiento en apoyo'),
    ('Balonmano', 'Lateral', 'Lanzamiento', 'Potencia de lanzamiento', 'Precisión de lanzamiento', 'Variedad de lanzamientos', 'Lanzamiento en salto', 'Lanzamiento en apoyo'),
    ('Balonmano', 'Lateral', '1vs1 ofensivo', 'Desborde', 'Cambio de ritmo', 'Finta', 'Penetración', 'Habilidad para sacar faltas'),
    ('Balonmano', 'Lateral', 'Pase', 'Precisión en el pase', 'Pase al pivote', 'Pase al extremo', 'Pase rápido', 'Pase en apoyo'),
    ('Balonmano', 'Lateral', 'Capacidad de salto', 'Salto vertical', 'Coordinación en el salto', 'Equilibrio en el aire', 'Lanzamiento en suspensión', 'Bloqueo en suspensión'),
    ('Balonmano', 'Lateral', 'Defensa lateral', 'Marcaje 1vs1', 'Agresividad defensiva', 'Velocidad lateral', 'Anticipación', 'Recuperación'),
    ('Balonmano', 'Extremo', 'Velocidad', 'Aceleración', 'Punta', 'Cambio de ritmo', 'Velocidad con balón', 'Sin balón'),
    ('Balonmano', 'Extremo', 'Definición', 'Precisión en el lanzamiento', 'Variedad de lanzamientos', 'Lanzamiento desde ángulo', 'Definición en contraataque', 'Tiro a portería'),
    ('Balonmano', 'Extremo', 'Salto', 'Salto vertical', 'Coordinación en el salto', 'Equilibrio en el aire', 'Lanzamiento en suspensión', 'Bloqueo en suspensión'),
    ('Balonmano', 'Extremo', 'Remate', 'Precisión del remate', 'Potencia del remate', 'Remate en salto', 'Remate en carrera', 'Definición'),
    ('Balonmano', 'Extremo', 'Repliegue defensivo', 'Velocidad de repliegue', 'Marcaje al lateral', 'Cobertura del central', 'Intensidad defensiva', 'Capacidad para recuperar'),
    ('Balonmano', 'Pivote', 'Bloqueos', 'Fuerza en el bloqueo', 'Precisión del bloqueo', 'Continuidad tras bloqueo', 'Bloqueo para el tirador', 'Bloqueo para la penetración'),
    ('Balonmano', 'Pivote', 'Continuidad', 'Movimiento sin balón', 'Desmarques', 'Ofrecimiento para el pase', 'Juego de pies', 'Apoyo ofensivo'),
    ('Balonmano', 'Pivote', 'Finalización', 'Ganchos', 'Tiros de corta distancia', 'Habilidad para recibir pases difíciles', 'Definición', 'Capacidad para girar'),
    ('Balonmano', 'Pivote', 'Defensa en 6 metros', 'Marcaje 1vs1', 'Fuerza defensiva', 'Bloqueo de lanzamientos', 'Comunicación con la defensa', 'Posicionamiento'),
    ('Balonmano', 'Pivote', 'Recepción de balón', 'Habilidad para recibir pases difíciles', 'Control de balón', 'Protección del balón', 'Recepción bajo presión', 'Pase de apoyo'),
    
    -- Voleibol
    ('Voleibol', 'Colocador', 'Pase', 'Precisión del pase', 'Velocidad del pase', 'Pase con una mano', 'Pase con dos manos', 'Pase en movimiento'),
    ('Voleibol', 'Colocador', 'Toma de decisiones', 'Lectura del bloqueo rival', 'Identificación del ataque', 'Elección de la jugada', 'Rapidez', 'Variedad de jugadas'),
    ('Voleibol', 'Colocador', 'Comunicación', 'Comunicación verbal', 'Comunicación no verbal', 'Liderazgo', 'Claridad en las indicaciones', 'Entendimiento con los atacantes'),
    ('Voleibol', 'Colocador', 'Bloqueo', 'Posicionamiento', 'Salto vertical', 'Penetración de manos', 'Lectura del ataque rival', 'Timing'),
    ('Voleibol', 'Colocador', 'Defensa', 'Recepción de saque', 'Defensa de campo', 'Agilidad', 'Movilidad', 'Cobertura'),
    ('Voleibol', 'Central', 'Bloqueo', 'Posicionamiento', 'Salto vertical', 'Penetración de manos', 'Lectura del ataque rival', 'Timing'),
    ('Voleibol', 'Central', 'Ataque rápido', 'Velocidad de ataque', 'Coordinación con el colocador', 'Remate', 'Variedad de ataques', 'Lectura del bloqueo'),
    ('Voleibol', 'Central', 'Saque', 'Potencia del saque', 'Precisión del saque', 'Saque de salto', 'Saque flotante', 'Estrategia de saque'),
    ('Voleibol', 'Central', 'Defensa en red', 'Movilidad lateral', 'Velocidad de reacción', 'Bloqueo', 'Anticipación', 'Comunicación'),
    ('Voleibol', 'Central', 'Movilidad lateral', 'Rapidez en el desplazamiento', 'Agilidad', 'Cambios de dirección', 'Recuperación', 'Posicionamiento'),
    ('Voleibol', 'Opuesto', 'Ataque de fuerza', 'Potencia de remate', 'Precisión de remate', 'Variedad de remates', 'Ataque desde segunda línea', 'Salto'),
    ('Voleibol', 'Opuesto', 'Bloqueo', 'Posicionamiento', 'Salto vertical', 'Penetración de manos', 'Lectura del ataque rival', 'Timing'),
    ('Voleibol', 'Opuesto', 'Saque', 'Potencia del saque', 'Precisión del saque', 'Saque de salto', 'Saque flotante', 'Estrategia de saque'),
    ('Voleibol', 'Opuesto', 'Defensa en segunda línea', 'Recepción de saque', 'Defensa de campo', 'Movilidad', 'Anticipación', 'Cobertura'),
    ('Voleibol', 'Opuesto', 'Recepción de balón', 'Precisión en la recepción', 'Control del balón', 'Lectura del saque rival', 'Posicionamiento', 'Movimiento'),
    ('Voleibol', 'Receptor-Atacante', 'Recepción', 'Precisión en la recepción', 'Control del balón', 'Lectura del saque rival', 'Posicionamiento', 'Movimiento'),
    ('Voleibol', 'Receptor-Atacante', 'Ataque', 'Potencia de remate', 'Precisión de remate', 'Variedad de remates', 'Ataque desde zona 4', 'Ataque desde segunda línea'),
    ('Voleibol', 'Receptor-Atacante', 'Defensa de campo', 'Agilidad', 'Movilidad', 'Reacción a balones rápidos', 'Cobertura', 'Posicionamiento'),
    ('Voleibol', 'Receptor-Atacante', 'Saque', 'Potencia del saque', 'Precisión del saque', 'Saque flotante', 'Saque de salto', 'Estrategia de saque'),
    ('Voleibol', 'Receptor-Atacante', 'Pase de colocación', 'Precisión del pase', 'Velocidad del pase', 'Pase de antebrazos', 'Pase de dedos', 'Control del balón'),
    ('Voleibol', 'Líbero', 'Recepción', 'Precisión en la recepción', 'Control del balón', 'Lectura del saque rival', 'Posicionamiento', 'Movimiento'),
    ('Voleibol', 'Líbero', 'Defensa de campo', 'Agilidad', 'Movilidad', 'Reacción a balones rápidos', 'Cobertura', 'Posicionamiento'),
    ('Voleibol', 'Líbero', 'Comunicación', 'Comunicación verbal', 'Comunicación no verbal', 'Liderazgo', 'Claridad en las indicaciones', 'Organización defensiva'),
    ('Voleibol', 'Líbero', 'Agilidad', 'Movilidad', 'Rapidez de reacción', 'Cambios de dirección', 'Flexibilidad', 'Equilibrio'),
    ('Voleibol', 'Líbero', 'Cobertura', 'Posicionamiento en defensa', 'Apoyo a los bloqueadores', 'Anticipación', 'Recuperación', 'Lectura de la jugada'),
    
    -- Atletismo
    ('Atletismo', 'Carreras de velocidad', 'Potencia de salida', 'Fuerza de piernas', 'Reacción al pistoletazo', 'Angulo de salida', 'Longitud de zancada en salida', 'Frecuencia de zancada en salida'),
    ('Atletismo', 'Carreras de velocidad', 'Frecuencia de zancada', 'Rapidez de piernas', 'Coordinación', 'Técnica de braceo', 'Eficiencia de movimiento', 'Ritmo'),
    ('Atletismo', 'Carreras de velocidad', 'Técnica de carrera', 'Postura', 'Zancada', 'Braceo', 'Apoyo del pie', 'Relajación'),
    ('Atletismo', 'Carreras de velocidad', 'Resistencia a la velocidad', 'Mantenimiento de la velocidad máxima', 'Aguante en el sprint', 'Recuperación', 'Tolerancia al lactato', 'Fuerza terminal'),
    ('Atletismo', 'Carreras de velocidad', 'Concentración', 'Foco en la salida', 'Mantener la línea', 'Conciencia espacial', 'Ignorar distracciones', 'Visualización'),
    ('Atletismo', 'Vallas', 'Coordinación', 'Ritmo entre vallas', 'Sincronización de movimientos', 'Paso de valla', 'Aterrizaje', 'Braceo'),
    ('Atletismo', 'Vallas', 'Ritmo de carrera', 'Constancia en la zancada', 'Aceleración entre vallas', 'Fluidez', 'Transición', 'Control del paso'),
    ('Atletismo', 'Vallas', 'Flexibilidad', 'Movilidad de cadera', 'Extensión de pierna', 'Amplitud de movimiento', 'Prevenir lesiones', 'Recuperación'),
    ('Atletismo', 'Vallas', 'Técnica de paso de valla', 'Ataque a la valla', 'Paso de la pierna de ataque', 'Paso de la pierna de batida', 'Recuperación tras valla', 'Economía de movimiento'),
    ('Atletismo', 'Vallas', 'Velocidad', 'Velocidad de carrera', 'Velocidad de reacción', 'Velocidad entre vallas', 'Aceleración', 'Punta'),
    ('Atletismo', 'Carreras de medio fondo', 'Resistencia aeróbica', 'Capacidad de mantener el esfuerzo', 'Gestión del oxígeno', 'Ritmo constante', 'Aguante muscular', 'Recuperación'),
    ('Atletismo', 'Carreras de medio fondo', 'Cambio de ritmo', 'Aceleración', 'Frenada', 'Variación de velocidad', 'Timing', 'Capacidad de respuesta'),
    ('Atletismo', 'Carreras de medio fondo', 'Estrategia de carrera', 'Posicionamiento', 'Gestión del esfuerzo', 'Toma de decisiones', 'Lectura de la carrera', 'Ataque final'),
    ('Atletismo', 'Carreras de medio fondo', 'Fuerza de zancada', 'Potencia de piernas', 'Amplitud de zancada', 'Frecuencia de zancada', 'Impulso', 'Explosividad'),
    ('Atletismo', 'Carreras de medio fondo', 'Final de carrera', 'Sprint final', 'Fuerza terminal', 'Mantenimiento de la técnica', 'Capacidad de sufrimiento', 'Remate'),
    ('Atletismo', 'Carreras de fondo', 'Resistencia', 'Capacidad aeróbica', 'Aguante muscular', 'Mantenimiento del ritmo', 'Recuperación', 'Tolerancia a la fatiga'),
    ('Atletismo', 'Carreras de fondo', 'Ritmo constante', 'Control de velocidad', 'Autoconocimiento', 'Mantenimiento del paso', 'Eficiencia energética', 'Regularidad'),
    ('Atletismo', 'Carreras de fondo', 'Gestión del esfuerzo', 'Dosificación de energía', 'Conciencia corporal', 'Toma de decisiones', 'Adaptación al terreno', 'Respuesta a la fatiga'),
    ('Atletismo', 'Carreras de fondo', 'Hidratación', 'Reposición de líquidos', 'Conocimiento de las necesidades', 'Timing de hidratación', 'Electrolitos', 'Prevención de calambres'),
    ('Atletismo', 'Carreras de fondo', 'Técnica de carrera eficiente', 'Economía de movimiento', 'Postura', 'Zancada', 'Braceo', 'Respiración'),
    ('Atletismo', 'Marcha', 'Técnica de marcha', 'Contacto del talón', 'Extensión de rodilla', 'Movimiento de cadera', 'Braceo', 'Coordinación'),
    ('Atletismo', 'Marcha', 'Resistencia', 'Aguante muscular', 'Capacidad aeróbica', 'Mantenimiento del ritmo', 'Tolerancia a la fatiga', 'Recuperación'),
    ('Atletismo', 'Marcha', 'Ritmo', 'Constancia en la zancada', 'Velocidad controlada', 'Eficiencia', 'Regulación', 'Control del paso'),
    ('Atletismo', 'Marcha', 'Descalificación', 'Conocimiento de la normativa', 'Técnica correcta', 'Evitar pérdida de contacto', 'Evitar rodilla doblada', 'Atención a los jueces'),
    ('Atletismo', 'Marcha', 'Concentración', 'Mantener la técnica', 'Conciencia corporal', 'Ignorar distracciones', 'Gestión del dolor', 'Control mental'),
    ('Atletismo', 'Salto de longitud', 'Velocidad de carrera', 'Aceleración', 'Punta', 'Ritmo de aproximación', 'Consistencia en la velocidad', 'Control de la velocidad'),
    ('Atletismo', 'Salto de longitud', 'Potencia de impulso', 'Fuerza de piernas', 'Explosividad', 'Amortiguación', 'Reacción al suelo', 'Coordinación'),
    ('Atletismo', 'Salto de longitud', 'Técnica de batida', 'Precisión de batida', 'Ángulo de batida', 'Pierna de batida', 'Brazo de batida', 'Movimiento del cuerpo'),
    ('Atletismo', 'Salto de longitud', 'Fase de vuelo', 'Posición del cuerpo', 'Movimientos de brazos', 'Movimientos de piernas', 'Equilibrio', 'Altura del salto'),
    ('Atletismo', 'Salto de longitud', 'Caída', 'Técnica de caída', 'Posición de piernas', 'Extensión del cuerpo', 'Seguridad', 'Distancia de caída'),
    ('Atletismo', 'Triple salto', 'Velocidad de carrera', 'Aceleración', 'Punta', 'Ritmo de aproximación', 'Consistencia en la velocidad', 'Control de la velocidad'),
    ('Atletismo', 'Triple salto', 'Potencia de impulso', 'Fuerza de piernas', 'Explosividad', 'Amortiguación', 'Reacción al suelo', 'Coordinación'),
    ('Atletismo', 'Triple salto', 'Técnica de salto (paso, salto)', 'Ritmo de saltos', 'Coordinación', 'Fuerza de cada fase', 'Equilibrio', 'Transición entre fases'),
    ('Atletismo', 'Triple salto', 'Coordinación', 'Sincronización de movimientos', 'Equilibrio', 'Fluidez', 'Ritmo', 'Control corporal'),
    ('Atletismo', 'Triple salto', 'Fase de vuelo', 'Posición del cuerpo', 'Movimientos de brazos', 'Movimientos de piernas', 'Equilibrio', 'Control de la trayectoria'),
    ('Atletismo', 'Salto de altura', 'Técnica de salto (Fosbury)', 'Aproximación en curva', 'Batida', 'Paso por el listón', 'Arqueo', 'Caída'),
    ('Atletismo', 'Salto de altura', 'Fuerza de piernas', 'Potencia de impulso', 'Fuerza en la batida', 'Explosividad', 'Salto vertical', 'Fuerza reactiva'),
    ('Atletismo', 'Salto de altura', 'Flexibilidad', 'Movilidad de cadera', 'Arqueo de espalda', 'Amplitud de movimiento', 'Prevención de lesiones', 'Recuperación'),
    ('Atletismo', 'Salto de altura', 'Coordinación', 'Sincronización de movimientos', 'Ritmo de carrera', 'Batida', 'Movimiento de brazos', 'Control corporal'),
    ('Atletismo', 'Salto de altura', 'Ritmo de carrera', 'Constancia en la zancada', 'Aceleración progresiva', 'Curva de aproximación', 'Velocidad controlada', 'Consistencia'),
    ('Atletismo', 'Salto con pértiga', 'Velocidad de carrera', 'Aceleración', 'Punta', 'Ritmo de aproximación', 'Consistencia en la velocidad', 'Control de la velocidad'),
    ('Atletismo', 'Salto con pértiga', 'Fuerza de brazos', 'Agarre de la pértiga', 'Tracción', 'Subida', 'Control', 'Estabilidad'),
    ('Atletismo', 'Salto con pértiga', 'Técnica de batida', 'Precisión de batida', 'Ángulo de batida', 'Momento de batida', 'Extensión de piernas', 'Empuje'),
    ('Atletismo', 'Salto con pértiga', 'Coordinación', 'Sincronización de movimientos', 'Ritmo', 'Equilibrio', 'Fluidez', 'Control corporal'),
    ('Atletismo', 'Salto con pértiga', 'Altura de agarre', 'Posición de agarre', 'Fuerza de agarre', 'Estabilidad', 'Control de la pértiga', 'Ajuste'),
    ('Atletismo', 'Lanzamiento de peso', 'Fuerza explosiva', 'Potencia de piernas', 'Fuerza de tronco', 'Fuerza de brazos', 'Velocidad de movimiento', 'Reacción'),
    ('Atletismo', 'Lanzamiento de peso', 'Técnica de lanzamiento', 'Posición inicial', 'Deslizamiento/giro', 'Posición de fuerza', 'Liberación del peso', 'Equilibrio'),
    ('Atletismo', 'Lanzamiento de peso', 'Equilibrio', 'Control corporal', 'Estabilidad en el giro', 'Mantener la posición', 'Recuperación', 'Prevenir caídas'),
    ('Atletismo', 'Lanzamiento de peso', 'Coordinación', 'Sincronización de movimientos', 'Fluidez del gesto', 'Transmisión de fuerza', 'Ritmo', 'Secuencia de movimientos'),
    ('Atletismo', 'Lanzamiento de peso', 'Potencia de piernas', 'Fuerza de empuje', 'Extensión de piernas', 'Generación de fuerza', 'Impulso', 'Explosividad'),
    ('Atletismo', 'Lanzamiento de disco', 'Técnica de giro', 'Velocidad de giro', 'Equilibrio en el giro', 'Posición del cuerpo', 'Transferencia de peso', 'Liberación del disco'),
    ('Atletismo', 'Lanzamiento de disco', 'Fuerza explosiva', 'Potencia de piernas', 'Fuerza de tronco', 'Fuerza de brazos', 'Velocidad de movimiento', 'Reacción'),
    ('Atletismo', 'Lanzamiento de disco', 'Equilibrio', 'Control corporal', 'Estabilidad en el giro', 'Mantener la posición', 'Recuperación', 'Prevenir caídas'),
    ('Atletismo', 'Lanzamiento de disco', 'Coordinación', 'Sincronización de movimientos', 'Fluidez del gesto', 'Transmisión de fuerza', 'Ritmo', 'Secuencia de movimientos'),
    ('Atletismo', 'Lanzamiento de disco', 'Velocidad angular', 'Aceleración del giro', 'Transferencia de energía', 'Velocidad de liberación', 'Rotación del cuerpo', 'Impulso'),
    ('Atletismo', 'Lanzamiento de martillo', 'Técnica de giro', 'Velocidad de giro', 'Equilibrio en el giro', 'Posición del cuerpo', 'Transferencia de peso', 'Liberación del martillo'),
    ('Atletismo', 'Lanzamiento de martillo', 'Fuerza', 'Fuerza de brazos', 'Fuerza de tronco', 'Fuerza de piernas', 'Resistencia a la fuerza centrífuga', 'Potencia'),
    ('Atletismo', 'Lanzamiento de martillo', 'Equilibrio', 'Control corporal', 'Estabilidad en el giro', 'Mantener la posición', 'Recuperación', 'Prevenir caídas'),
    ('Atletismo', 'Lanzamiento de martillo', 'Coordinación', 'Sincronización de movimientos', 'Fluidez del gesto', 'Transmisión de fuerza', 'Ritmo', 'Secuencia de movimientos'),
    ('Atletismo', 'Lanzamiento de martillo', 'Velocidad de lanzamiento', 'Aceleración del martillo', 'Velocidad del giro', 'Velocidad de liberación', 'Fuerza centrífuga', 'Control'),
    ('Atletismo', 'Lanzamiento de jabalina', 'Técnica de carrera', 'Velocidad de aproximación', 'Ritmo de carrera', 'Progresión de velocidad', 'Coordinación con el lanzamiento', 'Consistencia'),
    ('Atletismo', 'Lanzamiento de jabalina', 'Fuerza del brazo', 'Potencia de lanzamiento', 'Fuerza en el codo', 'Rotación del hombro', 'Extensión del brazo', 'Fuerza explosiva'),
    ('Atletismo', 'Lanzamiento de jabalina', 'Coordinación', 'Sincronización de movimientos', 'Fluidez del gesto', 'Transmisión de fuerza', 'Ritmo', 'Secuencia de movimientos'),
    ('Atletismo', 'Lanzamiento de jabalina', 'Velocidad de lanzamiento', 'Aceleración del brazo', 'Velocidad de la carrera', 'Velocidad de liberación', 'Fuerza explosiva', 'Impulso'),
    ('Atletismo', 'Lanzamiento de jabalina', 'Ángulo de salida', 'Ángulo óptimo', 'Control del ángulo', 'Ajuste del ángulo', 'Precisión del ángulo', 'Dominio del viento'),
    ('Atletismo', 'Pruebas combinadas', 'Versatilidad', 'Adaptación a diferentes disciplinas', 'Habilidad en múltiples técnicas', 'Capacidad de aprendizaje', 'Amplio rango de habilidades', 'Dominio de los fundamentos'),
    ('Atletismo', 'Pruebas combinadas', 'Resistencia', 'Aguante físico', 'Capacidad aeróbica', 'Recuperación entre pruebas', 'Tolerancia a la fatiga', 'Gestión del esfuerzo'),
    ('Atletismo', 'Pruebas combinadas', 'Fuerza', 'Fuerza muscular general', 'Fuerza explosiva', 'Potencia', 'Fuerza específica de cada disciplina', 'Resistencia a la fuerza'),
    ('Atletismo', 'Pruebas combinadas', 'Técnica en múltiples disciplinas', 'Dominio de la técnica de cada prueba', 'Eficiencia de movimiento', 'Precisión', 'Coordinación', 'Automatización'),
    ('Atletismo', 'Pruebas combinadas', 'Gestión del esfuerzo', 'Dosificación de energía', 'Conocimiento de las propias limitaciones', 'Recuperación activa', 'Alimentación', 'Hidratación'),
    
    -- Equitación
    ('Equitación', 'Salto de obstáculos', 'Precisión en el salto', 'Distancia', 'Altura', 'Trayectoria', 'Equilibrio en el salto', 'Control del batida'),
    ('Equitación', 'Salto de obstáculos', 'Control del caballo', 'Obediencia', 'Respuesta a las ayudas', 'Ritmo', 'Reunión', 'Extensión'),
    ('Equitación', 'Salto de obstáculos', 'Ritmo', 'Constancia', 'Velocidad adecuada', 'Cadencia', 'Fluidez', 'Control del galope'),
    ('Equitación', 'Salto de obstáculos', 'Valentía', 'Confianza', 'Determinación', 'Capacidad de superar el miedo', 'Gestión de la presión', 'Calma'),
    ('Equitación', 'Salto de obstáculos', 'Comunicación jinete-caballo', 'Ayudas', 'Sensibilidad', 'Entendimiento mutuo', 'Sincronización', 'Confianza'),
    ('Equitación', 'Doma clásica', 'Armonía', 'Sujeción', 'Contacto', 'Impulsión', 'Rectitud', 'Fluidez de movimientos'),
    ('Equitación', 'Doma clásica', 'Sujeción', 'Mano', 'Riendas', 'Asiento', 'Piernas', 'Comunicación'),
    ('Equitación', 'Doma clásica', 'Impulsión', 'Energía', 'Propulsión', 'Actividad de los posteriores', 'Transmisiones', 'Ritmo'),
    ('Equitación', 'Doma clásica', 'Rectitud', 'Alineación del caballo', 'Equilibrio', 'Control de los posteriores', 'Control de los anteriores', 'Flexibilidad'),
    ('Equitación', 'Doma clásica', 'Obediencia del caballo', 'Respuesta a las ayudas', 'Voluntad de trabajo', 'Atención', 'Calma', 'Confianza'),
    ('Equitación', 'Concurso completo', 'Versatilidad', 'Habilidad en doma', 'Habilidad en salto', 'Habilidad en cross-country', 'Adaptación a diferentes terrenos', 'Dominio de diferentes técnicas'),
    ('Equitación', 'Concurso completo', 'Resistencia del caballo', 'Condición física del caballo', 'Recuperación del caballo', 'Gestión del esfuerzo', 'Resistencia cardiovascular', 'Fuerza muscular'),
    ('Equitación', 'Concurso completo', 'Precisión', 'Exactitud en los ejercicios', 'Trayectoria en el salto', 'Control en el cross-country', 'Tiempos', 'Recorrido'),
    ('Equitación', 'Concurso completo', 'Habilidad en distintas disciplinas', 'Doma', 'Salto', 'Cross-country', 'Manejo en diferentes situaciones', 'Adaptación'),
    ('Equitación', 'Concurso completo', 'Gestión del esfuerzo', 'Dosificación de energía del caballo', 'Conocimiento de las limitaciones', 'Recuperación entre pruebas', 'Alimentación', 'Hidratación'),
    ('Equitación', 'Raid', 'Resistencia del caballo', 'Condición física del caballo', 'Recuperación del caballo', 'Gestión del esfuerzo', 'Resistencia cardiovascular', 'Fuerza muscular'),
    ('Equitación', 'Raid', 'Gestión de la energía', 'Dosificación del esfuerzo', 'Hidratación', 'Alimentación', 'Conocimiento del caballo', 'Ritmo de carrera'),
    ('Equitación', 'Raid', 'Orientación', 'Lectura de mapas', 'Uso de brújula', 'Seguimiento de rutas', 'Reconocimiento del terreno', 'Toma de decisiones'),
    ('Equitación', 'Raid', 'Cuidado del caballo', 'Inspección veterinaria', 'Alimentación', 'Hidratación', 'Reconocimiento de fatiga', 'Primeros auxilios'),
    ('Equitación', 'Raid', 'Ritmo de carrera', 'Velocidad controlada', 'Consistencia', 'Adaptación al terreno', 'Mantenimiento del ritmo cardíaco', 'Estrategia de carrera'),
    ('Equitación', 'Enganche', 'Precisión', 'Control de la dirección', 'Trazado de curvas', 'Espacio', 'Coordinación con los caballos', 'Exactitud'),
    ('Equitación', 'Enganche', 'Control del equipo', 'Manejo de riendas', 'Manejo de los caballos', 'Equilibrio del carruaje', 'Seguridad', 'Confianza'),
    ('Equitación', 'Enganche', 'Habilidad en giros', 'Radio de giro', 'Control de la velocidad', 'Coordinación de los caballos', 'Estabilidad', 'Precisión'),
    ('Equitación', 'Enganche', 'Manejo de los caballos', 'Comunicación', 'Obediencia', 'Armonía', 'Control de la impulsión', 'Entendimiento'),
    ('Equitación', 'Enganche', 'Coordinación', 'Sincronización de movimientos', 'Trabajo en equipo con los caballos', 'Fluidez', 'Ritmo', 'Precisión'),
    ('Equitación', 'Volteo', 'Equilibrio', 'Estabilidad sobre el caballo', 'Control del cuerpo', 'Balance', 'Adaptación al movimiento', 'Fuerza del core'),
    ('Equitación', 'Volteo', 'Flexibilidad', 'Amplitud de movimientos', 'Elasticidad', 'Movilidad articular', 'Prevenir lesiones', 'Recuperación'),
    ('Equitación', 'Volteo', 'Fuerza', 'Fuerza de brazos', 'Fuerza de piernas', 'Fuerza del core', 'Resistencia muscular', 'Potencia'),
    ('Equitación', 'Volteo', 'Coordinación', 'Sincronización de movimientos', 'Ritmo con el caballo', 'Fluidez', 'Control corporal', 'Secuencia de movimientos'),
    ('Equitación', 'Volteo', 'Trabajo en equipo (con el caballo)', 'Confianza', 'Comunicación no verbal', 'Entendimiento mutuo', 'Sincronización', 'Armonía'),
    ('Equitación', 'Horseball', 'Agilidad', 'Rapidez de movimientos', 'Cambios de dirección', 'Coordinación', 'Habilidad con el balón', 'Velocidad de reacción'),
    ('Equitación', 'Horseball', 'Coordinación', 'Sincronización de movimientos', 'Comunicación con el caballo', 'Manejo del balón', 'Pase', 'Tiro'),
    ('Equitación', 'Horseball', 'Pase', 'Precisión del pase', 'Fuerza del pase', 'Pase en movimiento', 'Pase al compañero', 'Visión de juego'),
    ('Equitación', 'Horseball', 'Tiro a canasta', 'Precisión del tiro', 'Fuerza del tiro', 'Tiro en movimiento', 'Tiro a distancia', 'Selección de tiro'),
    ('Equitación', 'Horseball', 'Trabajo en equipo', 'Comunicación', 'Apoyo', 'Desmarque', 'Coberturas', 'Estrategia'),
    ('Equitación', 'Doma vaquera', 'Control del caballo', 'Obediencia', 'Respuesta a las ayudas', 'Riendas', 'Asiento', 'Piernas'),
    ('Equitación', 'Doma vaquera', 'Agilidad', 'Maniobras rápidas', 'Giros', 'Paradas', 'Arrancadas', 'Cambios de ritmo'),
    ('Equitación', 'Doma vaquera', 'Precisión en movimientos', 'Exactitud en figuras', 'Transiciones', 'Paradas', 'Giros', 'Control'),
    ('Equitación', 'Doma vaquera', 'Comunicación con el caballo', 'Ayudas sutiles', 'Sensibilidad', 'Entendimiento mutuo', 'Confianza', 'Respuesta'),
    ('Equitación', 'Doma vaquera', 'Tradición', 'Conocimiento de la disciplina', 'Estilo', 'Indumentaria', 'Respeto por las raíces', 'Pasión'),
    ('Equitación', 'Ponis', 'Manejo básico del poni', 'Control de la dirección', 'Parar', 'Arrancar', 'Giros', 'Comunicación con el poni'),
    ('Equitación', 'Ponis', 'Equilibrio', 'Estabilidad sobre el poni', 'Postura', 'Balance', 'Adaptación al movimiento', 'Control del cuerpo'),
    ('Equitación', 'Ponis', 'Seguridad', 'Atención a las normas', 'Uso del equipo de protección', 'Supervisión', 'Conciencia del entorno', 'Prevención de riesgos'),
    ('Equitación', 'Ponis', 'Confianza', 'Calma', 'Paciencia', 'Comunicación', 'Establecer un vínculo', 'Superar el miedo'),
    ('Equitación', 'Ponis', 'Juego en equipo', 'Cooperación', 'Respeto', 'Comunicación', 'Ayuda a compañeros', 'Participación'),
    ('Equitación', 'Paraecuestre', 'Adaptación', 'Uso de ayudas adaptadas', 'Manejo de la discapacidad', 'Ajuste de la técnica', 'Resiliencia', 'Creatividad'),
    ('Equitación', 'Paraecuestre', 'Comunicación con el caballo', 'Ayudas específicas', 'Sensibilidad', 'Entendimiento mutuo', 'Confianza', 'Paciencia'),
    ('Equitación', 'Paraecuestre', 'Equilibrio', 'Estabilidad sobre el caballo', 'Postura', 'Balance', 'Fuerza del core', 'Adaptación al movimiento'),
    ('Equitación', 'Paraecuestre', 'Fuerza', 'Fuerza muscular relevante', 'Resistencia', 'Potencia', 'Fuerza funcional', 'Control'),
    ('Equitación', 'Paraecuestre', 'Precisión', 'Exactitud en los ejercicios', 'Control de la trayectoria', 'Respuesta del caballo', 'Ejecución de figuras', 'Detalle'),
    ('Equitación', 'Reining', 'Control preciso', 'Riendas', 'Asiento', 'Piernas', 'Comunicación sutil', 'Obediencia del caballo'),
    ('Equitación', 'Reining', 'Maniobras específicas', 'Sliding stops', 'Spins', 'Rollbacks', 'Circles', 'Cambios de galope'),
    ('Equitación', 'Reining', 'Agilidad del caballo', 'Rapidez de movimientos', 'Cambios de dirección', 'Flexibilidad', 'Velocidad de reacción', 'Equilibrio'),
    ('Equitación', 'Reining', 'Velocidad controlada', 'Ritmo', 'Aceleración', 'Frenada', 'Transiciones', 'Dominio de la velocidad'),
    ('Equitación', 'Reining', 'Comunicación jinete-caballo', 'Ayudas imperceptibles', 'Sensibilidad', 'Entendimiento mutuo', 'Confianza', 'Armonía'),
    ('Equitación', 'Trec', 'Orientación', 'Lectura de mapas', 'Uso de brújula', 'Seguimiento de rutas', 'Reconocimiento del terreno', 'Toma de decisiones'),
    ('Equitación', 'Trec', 'Control del caballo', 'Obediencia', 'Respuesta a las ayudas', 'Equilibrio', 'Manejo en diferentes terrenos', 'Confianza'),
    ('Equitación', 'Trec', 'Adaptación al terreno', 'Movimiento en subidas', 'Movimiento en bajadas', 'Cruzar obstáculos naturales', 'Paso por agua', 'Superficies irregulares'),
    ('Equitación', 'Trec', 'Superación de obstáculos naturales', 'Franqueo', 'Saltos pequeños', 'Pasos complicados', 'Determinación', 'Confianza'),
    ('Equitación', 'Trec', 'Resistencia', 'Aguante del caballo', 'Aguante del jinete', 'Gestión del esfuerzo', 'Recuperación', 'Hidratación'),
    ('Equitación', 'Turismo ecuestre', 'Manejo básico', 'Control de la dirección', 'Parar', 'Arrancar', 'Giros', 'Comunicación con el caballo'),
    ('Equitación', 'Turismo ecuestre', 'Conocimiento del terreno', 'Lectura de mapas', 'Orientación', 'Identificación de peligros', 'Planificación de rutas', 'Seguridad'),
    ('Equitación', 'Turismo ecuestre', 'Cuidado del caballo', 'Alimentación', 'Hidratación', 'Reconocimiento de fatiga', 'Primeros auxilios', 'Bienestar animal'),
    ('Equitación', 'Turismo ecuestre', 'Orientación', 'Lectura de mapas', 'Uso de brújula', 'Seguimiento de rutas', 'Reconocimiento del terreno', 'Toma de decisiones'),
    ('Equitación', 'Turismo ecuestre', 'Disfrute del entorno', 'Conciencia ambiental', 'Respeto por la naturaleza', 'Adaptación al ritmo', 'Convivencia', 'Aprecio del paisaje'),
    ('Equitación', 'Equitación de trabajo', 'Habilidad con el ganado', 'Control del caballo', 'Movimientos específicos', 'Agilidad', 'Precisión', 'Comunicación'),
    ('Equitación', 'Equitación de trabajo', 'Control del caballo', 'Obediencia', 'Respuesta a las ayudas', 'Riendas', 'Asiento', 'Piernas'),
    ('Equitación', 'Equitación de trabajo', 'Agilidad', 'Maniobras rápidas', 'Giros', 'Paradas', 'Arrancadas', 'Cambios de ritmo'),
    ('Equitación', 'Equitación de trabajo', 'Precisión', 'Exactitud en los movimientos', 'Control de la trayectoria', 'Respuesta del caballo', 'Ejecución de tareas', 'Detalle'),
    ('Equitación', 'Equitación de trabajo', 'Comunicación con el caballo', 'Ayudas sutiles', 'Sensibilidad', 'Entendimiento mutuo', 'Confianza', 'Respuesta'),
    
    -- Tenis
    ('Tenis', 'Individual', 'Saque', 'Velocidad del saque', 'Precisión del saque', 'Variedad de saques', 'Efecto', 'Colocación'),
    ('Tenis', 'Individual', 'Resto', 'Control de la dirección', 'Profundidad', 'Anticipación', 'Potencia', 'Devolución del servicio'),
    ('Tenis', 'Individual', 'Movimiento en pista', 'Velocidad', 'Agilidad', 'Resistencia', 'Anticipación', 'Recuperación'),
    ('Tenis', 'Individual', 'Mentalidad', 'Concentración', 'Determinación', 'Resiliencia', 'Gestión de la presión', 'Calma'),
    ('Tenis', 'Individual', 'Golpes de fondo', 'Profundidad', 'Velocidad', 'Efecto', 'Control', 'Consistencia'),
    ('Tenis', 'Dobles lado derecho', 'Volea', 'Precisión', 'Control', 'Velocidad de reacción', 'Posicionamiento en la red', 'Profundidad'),
    ('Tenis', 'Dobles lado derecho', 'Saque', 'Precisión', 'Efecto', 'Velocidad', 'Colocación para el compañero', 'Variedad'),
    ('Tenis', 'Dobles lado derecho', 'Posicionamiento en red', 'Anticipación', 'Cobertura', 'Movilidad', 'Comunicación', 'Control del espacio'),
    ('Tenis', 'Dobles lado derecho', 'Coordinación con el compañero', 'Comunicación', 'Entendimiento mutuo', 'Sincronización', 'Coberturas', 'Estrategia'),
    ('Tenis', 'Dobles lado derecho', 'Resto agresivo', 'Profundidad', 'Velocidad', 'Dirección', 'Buscar la red', 'Presión al saque'),
    ('Tenis', 'Dobles lado izquierdo', 'Resto', 'Control de la dirección', 'Profundidad', 'Anticipación', 'Potencia', 'Devolución del servicio'),
    ('Tenis', 'Dobles lado izquierdo', 'Devolución de saque', 'Precisión', 'Profundidad', 'Colocación', 'Efecto', 'Variedad'),
    ('Tenis', 'Dobles lado izquierdo', 'Movimiento en paralelo', 'Coordinación con el compañero', 'Sincronización', 'Cobertura', 'Desplazamiento', 'Espacio'),
    ('Tenis', 'Dobles lado izquierdo', 'Comunicación con el compañero', 'Comunicación verbal', 'Comunicación no verbal', 'Entendimiento mutuo', 'Estrategia', 'Confianza'),
    ('Tenis', 'Dobles lado izquierdo', 'Juego desde el fondo', 'Profundidad', 'Velocidad', 'Efecto', 'Control', 'Consistencia')
) AS movimiento_data(deporte_nombre, posicion_nombre, nombre_movimiento, caracteristica_1, caracteristica_2, caracteristica_3, caracteristica_4, caracteristica_5)
JOIN deportes d ON d.nombre = movimiento_data.deporte_nombre
JOIN posiciones p ON p.nombre = movimiento_data.posicion_nombre AND p.deporte_id = d.id
WHERE NOT EXISTS (
  SELECT 1 FROM posicion_movimientos pm 
  WHERE pm.posicion_id = p.id 
  AND pm.nombre_movimiento = movimiento_data.nombre_movimiento
);
